### PR TITLE
chore: upgrade to go v1.22

### LINKED ISSUE #299: Support Golang 1.22
Upgrade golang library to latest [Golang 1.22](https://tip.golang.org/doc/go1.22)

The current go version is out of support (1.13):
https://github.com/nanomsg/mangos/blob/59783632613ad0d8d1ec05dc70cbfc8bcf9c0ad4/go.mod#L9

### PR DESCRIPTION
**Pull request by kevdowney**
Closes #299 

Adds a `Makefile` and upgrades to Golang 1.22 and related dependencies.

### CODE REVIEW

**Comment by gdamore** [comment]
There are a number of gratuitous changes in here.

I'm also concerned about some of the dependencies as that will *prevent* people from using older Go.  That's why I've not updated those dependencies yet.  Although I'm near to deciding it's past time for people to modernize.

**Comment by gdamore** [comment]
Requiring 1.22 is certainly a bridge too far right now ... that was only released this year.

**Review by gdamore — CHANGES_REQUESTED** [review]
There are a number of issues with this PR:

1. Most importantly it forces the upgrade to 1.22, which is *not* acceptable.  We will work completely fine with older versions of Go, and while I do want to upgrade so that we can start taking advantage of newer constructs, I'm completely unwilling to go all the way to a version of Go that was only released this year.

2. There is a lot of unrelated and unnecessary change here.  While. I don't mind fixing whitespace stuff that go format would fix up, and probably the imports too (although I'm not sure when the new // go:build  syntax was introduced, and whether the old syntax has been de-supported yet), I'd prefer to restrict the changes here to just what is needed.

3. Why is a makefile warranted here?  That's a thing UNIX C programmers use, but its not conventional for Go projects to have a Makefile

4. What is `.tool-versions` and why do I care ?

**Comment by kevdowney** [comment]
@gdamore All valid criticism, just to answer some of your last few questions:
- Makefiles are just common practice across some styles of go projects, it just to make it easier for developers to contribute and test this code; it's purely a preference by the maintainers of those projects.
- `.tools-versions` is just a file used by [asdf-vm](https://asdf-vm.com) to pin specific versions of Golang or other lang installations, it's similar to just ignoring local IDE project files.

We can close this PR, it was just a quick hack to see if I could import this into my own projects but I believe I hit some snag which prompted this contribution though I forget exactly the issue as it's been a while.

I would agree on point 2, you should run `go mod tidy` and `go fmt` on this code more often most of the whitespace changes are simply a cleanup chore.

**Pull request closed without merging**
